# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 751106aac2f1e628d9a66a1fbd43e54e8b1cb23ce6b23ca52c0ffad0f10ee7e322b2c4d8d47db40a886c180545c7322db91bfb16283971d0bce0cad9f6ae3287

test:
  secret_key_base: d9c616a2df81f44d9a9e5d34b7d060529966a2a8487bb17039eb1256a6a2138f29028af41c455877e80a1be51f567e2ebaf7bb985cdb15385837652f721f5c8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
